### ISSUE TITLE
Migrations do not migrate

### ISSUE THREAD

**Issue by richardpetithory** [owocki/pytrader#12]
I've tried running the shipped migrations and it seems that they may may have gone out of sync with one another at some point in time around 12 or 13. I attempted removing the migrations directory and running `makemigrations` from anew and everything seems to run well, so it make be good to do this permanently in the repo; to ditch the existing migration files and ship a single base migration and any other further OSS changes can be applied on top.

It looks like the only data migrations in place are:
* `0013_auto_20160222_2046.py`
* `0025_auto_20160224_1450.py`
* `0027_auto_20160224_1543.py`
* `0031_auto_20160224_2219.py`

All of which appear to be simple updates for existing data during development and are irrelevant to any newly created databases.

**Comment by owocki** [comment]
Hi @richardpetithory -  thanks for the issue report.  Ill take a look at this tonight / tommorrow.  If you have a moment, would  you mind submitting a PR with a clean slate of database migrations?  To your point, there were a handful of migrations created during development the last several months that are not necessary to the long term health of this repo.

**Comment by owocki** [comment]
closing due to merged PR
