### ISSUE TITLE
wont migrate; django error

### ISSUE THREAD

**Issue by kristerfl** [owocki/pytrader#14]
Hi I have set up everything and trying to run: manage.py migrate, but get a long error message ending in:

"base.py line 21, in complain raise ImproperlyConfigured("settings.DATABASES is improperly configured. "
django.core.exceptations.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.

**Comment by owocki** [comment]
HI @kristerfl try either of the following settings for `settings.DATABASE`.  The former requires postgres, the latter will run off of your file system.

```
#postgres

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',  # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'NAME': 'trader',                      # Or path to database file if using sqlite3.
        # The following settings are not used with sqlite3:
        'USER': 'trader',
        'PASSWORD': '<pw>',
        'HOST': '127.0.0.1',  # '127.0.0.1',                      # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'PORT': '',  # '5124',                      # Set to empty string for default.
        'ATOMIC_REQUESTS': True,
    },
}

```


```
#sqllite

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

_DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

```

**Comment by owocki** [comment]
feel free to reopen if you still have issues.

**Comment by kristerfl** [comment]
I have all that in that file. Could be I'm using wrong version for some of the reqs but not django and i still get the "django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details." on a fresh install..

**Comment by kristerfl** [comment]
i tried some tinkering and now have: 

Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/home/syntacs/.local/lib/python2.7/site-packages/django/__init__.py", line 1, in <module>
    from django.utils.version import get_version
  File "/home/syntacs/.local/lib/python2.7/site-packages/django/utils/version.py", line 5, in <module>
    import subprocess
  File "/usr/local/lib/python2.7/subprocess.py", line 429, in <module>
    import select
ImportError: /usr/local/lib/python2.7/lib-dynload/select.so: undefined symbol: _PyInt_AsInt
