### ISSUE TITLE
Support BTCC

### ISSUE THREAD

**Issue by joelwallis** [owocki/pytrader#29]
Interesting project. I could see that you have made some bitcoins from these trades but the Poloniex fee rates are high. Why not support [BTCC](https://www.btcc.com/)? It doesn't charge fees for trading. :-)

**Comment by owocki** [comment]
Thanks for the comment.  There's been some discussion of strategies to manage fees@ https://github.com/owocki/pytrader/issues/5 -- integrating with a low-fee or no-fee exchange is certainly an attractive option.

**Comment by joelwallis** [comment]
Good to know! Moving the suggestion to #5 and closing this one.

**Comment by owocki** [comment]
Thanks.  its a good suggestion!  Feel free to sign up to the slack -- We are organizing contributions in a more immediate way there https://github.com/owocki/pytrader/issues/23
