### ISSUE TITLE
Documentation on how to optimize the NN/classifiers

### ISSUE THREAD

**Issue by owocki** [owocki/pytrader#30]
predict_many_sk and predict_many_v2 jobs, how to optimize them.

im going to write up a little more on this, there are a handful of folks who have gotten the repo actually up and running and have been asking questions about how to optimize the trading engine.

**Comment by owocki** [comment]
```
* What is a ClassifierTest? A PredictionTest?
* Tuning c/nn's overview
* How to add other pairs
* How to adjust granularity
* Trader.py overview
```

**Comment by gptools-org** [comment]
- A typical workflow to get the bot trading
- Can we trade in simulation mode?
- How are the results calculated?
- Are there take profit (TP) and stop loss (SL) settings?
- How to adjust SL and TP levels?
- How are they determined (SL / TP), manually or auto?
- How many trades can be entered at any given time? Can this be adjusted?
- After tuning how will we know if our results are better or worse?
- How do we reset the algorithms?
- Can multiple instruments be traded? How to tell pytrader which instruments to trade?
- Is there a 'max time in trade' setting after which the position is closed? How to adjust?

**Comment by owaice** [comment]
```
-     A typical workflow to get the bot trading
-     Can we trade in simulation mode?
-     How are the results calculated?
-     Are there take profit (TP) and stop loss (SL) settings?
-     How to adjust SL and TP levels?
-     How are they determined (SL / TP), manually or auto?
-     How many trades can be entered at any given time? Can this be adjusted?
-     After tuning how will we know if our results are better or worse?
-     How do we reset the algorithms?
-     Can multiple instruments be traded? How to tell pytrader which instruments to trade?
-     Is there a 'max time in trade' setting after which the position is closed? How to adjust?

```

**Comment by owocki** [comment]
@owaice see https://github.com/owocki/pytrader/pull/40
