### ISSUE TITLE
linting standard

### ISSUE THREAD

**Issue by owocki** [owocki/pytrader#63]
Choose a standard and start enforcing it so that the code does not become a mess, style-wise.

pep8?

**Comment by igorpejic** [comment]
We could close this, since pep8 is being forced by travis CI.
Max-line length has been agreed to 120 and can be changed in [tox.ini](https://github.com/owocki/pytrader/blob/80c8f1f68238e3f45c9fcf02f658d8222bfe5460/tox.ini).
